#! /bin/sh

sxhkd &
compton --config /home/carlos/.config/compton/compton.conf &
xmodmap .mouseconfig &
xmodmap .speedswapper &
feh --bg-fill --randomize /home/carlos/Imágenes/Wallpapers/ &
xfce4-panel &
xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
