#! /bin/sh

#----Autostart
sxhkd &
compton --config /home/carlos/.config/compton/compton.conf &
xmodmap .mouseconfig &
xmodmap .speedswapper &
feh --bg-fill --randomize /home/carlos/Imágenes/Wallpapers/ &
#killall "tint2" 
tint2 &
xsetroot -cursor_name left_ptr &
#cbatticon &
#volti &
#nm-applet &
#/home/carlos/.config/lemonbar/launchlemon &

#----Workspace distribution per monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10


#----BSPWM's graphical appearance
bspc config border_width         2
bspc config window_gap          10
bspc config normal_border_color "#7c818c"
bspc config active_border_color "383c4a"
bspc config focused_border_color "#5294e2"
bspc config presel_feedback_color "#5294e2"


#----BSPWM's tiling rules:
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


#----BSPWM's applications rules:
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Xmessage state=floating
